---
# Normally, this would be set to the hostname of your DigitalOcean Droplet.
drupal_domain: "wieting.summittdweller.com"
vagrant_hostname: "{{ drupal_domain }}"

# Add only the `apache_vhosts` or `nginx_hosts` you need. If installing a
# single Drupal site, the variable should look like this (Apache):
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Since this will be a publicly-accessible instance of Drupal VM, make sure you
# configure secure passwords, especially for Drupal and MySQL!
drupal_db_user: wieting
drupal_db_password: mi3ting
drupal_db_name: wieting
drupal_site_name: "Wieting"
drupal_account_name: "System Admin"
drupal_account_pass: sawdust60
mysql_root_password: sawdust60

# Only install extras that you will need/use on your site, and don't install
# development-related software on production environments!
installed_extras:
  - drush
  - varnish
  - xdebug

# Disable Apache package upgrades.
apache_packages_state: installed

# Disable the dashboard page. Also remove any unneeded virtualhosts.
dashboard_install_dir: ''

# Enable a more hardened security configuration.
extra_security_enabled: true

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

# Set Apache to listen on port 81 (internal only), and Varnish on 80.
apache_listen_port: "81"
varnish_listen_port: "80"
varnish_default_backend_port: "81"

# Multi-site additions, if added, should conform to http://docs.drupalvm.com/en/latest/deployment/multisite/

# Enable XDEBUG for PHPSTORM per http://docs.drupalvm.com/en/latest/extras/xdebug/
php_xdebug_default_enable: 1
php_xdebug_idekey: PHPSTORM

drupal_composer_dependencies:
  - "drupal/devel:*"
  - "drupal/bootstrap:*"
  - "drupal/profile:*"
  - "drupal/pathauto:*"
  - "drupal/calendar:*"
  - "drupal/views_templates:*"
  - "drupal/google_analytics:*"
  - "drupal/embed:*"
  - "drupal/entity_embed:*"
  - "drupal/taxonomy_menu:*"
  - "drupal/blog:*"
  - "drupal/hms_field:*"
  - "drupal/entity_clone:*"
  - "drupal/rules:*"
  - "drupal/examples:*"



